services:
  api:
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rommanel
      POSTGRES_PASSWORD: rommanel
      POSTGRES_DB: rommaneldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
